# Generated by Django 3.0.2 on 2020-01-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
        ('gestion_consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fk_Profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesional', to='gestion_clinica.Profesional'),
        ),
    ]
