# Generated by Django 3.0.2 on 2020-01-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultas', '0002_auto_20200131_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=999, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=999, verbose_name='Altura (cm)'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mass',
            field=models.PositiveIntegerField(blank=True, default=999, verbose_name='Peso (kg)'),
        ),
    ]
