# Generated by Django 3.0.2 on 2020-01-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('idClinica', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('nif', models.CharField(blank=True, max_length=25, unique=True, verbose_name='NIF')),
                ('clinicname', models.CharField(max_length=100, verbose_name='Nombre Clínica')),
                ('ownerfullname', models.CharField(max_length=100, verbose_name='Nombre Titular')),
                ('numcolegiado', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Colegiado/a')),
                ('fulladdress', models.CharField(max_length=250, verbose_name='Dirección')),
                ('postcode', models.PositiveIntegerField(verbose_name='C.Postal')),
                ('city', models.CharField(max_length=50, verbose_name='Localidad')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='Provincia')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone1', models.PositiveIntegerField(verbose_name='Teléfono 1')),
                ('phone2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono 2')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('picturefile', models.ImageField(blank=True, null=True, upload_to='clinica/', verbose_name='LOGO')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('idConsultorio', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('officeID', models.CharField(max_length=10, unique=True, verbose_name='Denom./Identif.')),
                ('officeDesc', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('officeIsavail', models.BooleanField(default=True, verbose_name='Operativo')),
                ('officeLocation', models.CharField(blank=True, max_length=50, verbose_name='Localización')),
                ('officeDepartment', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('officeEquipment', models.TextField(blank=True, verbose_name='Equipamiento')),
                ('officePhone', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('officeNotes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'ordering': ['officeID'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('oto_Profesional', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profesionales', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('dni', models.CharField(max_length=9, unique=True, verbose_name='DNI')),
                ('nif', models.CharField(blank=True, max_length=25, verbose_name='NIF')),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre')),
                ('numcolegiado', models.CharField(blank=True, max_length=25, verbose_name='Número Colegiado/a')),
                ('position', models.CharField(max_length=100, verbose_name='Empleo/Puesto/Cargo')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('fulladdress', models.CharField(max_length=250, verbose_name='Dirección')),
                ('postcode', models.PositiveIntegerField(verbose_name='Cód. Postal')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='País')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('phone1', models.PositiveIntegerField(verbose_name='Teléfono principal')),
                ('phone2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono alternativo')),
                ('currentavail', models.BooleanField(default=True, verbose_name='De alta')),
                ('currentstaff', models.BooleanField(default=True, verbose_name='En plantilla')),
                ('picturefile', models.ImageField(blank=True, upload_to='profesionales/')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('area', models.CharField(blank=True, max_length=150, verbose_name='Area/Ambito')),
                ('fulladdress', models.CharField(max_length=250, verbose_name='Dirección')),
                ('nif', models.CharField(blank=True, max_length=25, verbose_name='NIF')),
                ('owner', models.CharField(blank=True, max_length=25, verbose_name='Propietario')),
                ('isManufact', models.BooleanField(default=False, verbose_name='Es fabricante')),
                ('phoneManufact', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('contactManufact', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('emailManufact', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('isProveedor', models.BooleanField(default=False, verbose_name='Es proveedor')),
                ('phoneProveedor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('contactProveedor', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('emailProveedor', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('isSAT', models.BooleanField(default=False, verbose_name='Es S.A.T.')),
                ('phoneSAT', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono fabricante')),
                ('contactSAT', models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto')),
                ('emailSAT', models.EmailField(blank=True, max_length=75, verbose_name='Email')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('idEquipamiento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('equipID', models.CharField(max_length=50, unique=True, verbose_name='Refer./Ident./Num. Serie')),
                ('equipDesc', models.CharField(max_length=100, verbose_name='Descripción')),
                ('equipType', models.CharField(choices=[('infor', 'Equipos informáticos'), ('muscl', 'Máquinas musculación'), ('eqtrm', 'Equipos tratamiento'), ('enfer', 'Enfermería'), ('fung', 'Fungible'), ('mobi', 'Mobiliario'), ('papel', 'Papelería'), ('limp', 'Limpieza'), ('otros', 'Otros')], default='otros', max_length=5, verbose_name='Tipo/Clase de Equip./Mat.')),
                ('equipIsavail', models.BooleanField(default=True, verbose_name='Control Operatividad')),
                ('equipDepartment', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('stockwarning', models.BooleanField(default=True, verbose_name='Control Stock')),
                ('stocklimit', models.PositiveIntegerField(default=10, verbose_name='Límite de aviso (unids.)')),
                ('stockavail', models.PositiveIntegerField(default=0, verbose_name='Stock actual (unids.)')),
                ('stockratio', models.PositiveIntegerField(blank=True, default=0)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
                ('fk_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizaciones', to='gestion_clinica.Consultorio')),
                ('fk_Manufact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantes', to='gestion_clinica.Proveedor')),
                ('fk_Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='gestion_clinica.Proveedor')),
                ('fk_SAT', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sats', to='gestion_clinica.Proveedor')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['equipID'],
            },
        ),
    ]
