# Generated by Django 3.0.2 on 2020-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='numcolegiado',
            field=models.CharField(blank=True, max_length=25, verbose_name='Núm. Colegiado/a'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='phone1',
            field=models.PositiveIntegerField(verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='phone2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Puesto/Cargo'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='postcode',
            field=models.PositiveIntegerField(verbose_name='Código Postal'),
        ),
    ]
