# Generated by Django 3.0 on 2019-12-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='idClinica',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='nif',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='NIF'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='numcolegiado',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número colegiado/a'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='picturefile',
            field=models.ImageField(blank=True, null=True, upload_to='clinica/', verbose_name='Archivo LOGO'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='postcode',
            field=models.PositiveIntegerField(verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officeID',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número/Identificación'),
        ),
    ]
