# Generated by Django 3.0 on 2019-12-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultorio',
            options={'ordering': ['officeID'], 'verbose_name': 'Consultorio', 'verbose_name_plural': 'Consultorios'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['fullname'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officeID',
            field=models.CharField(max_length=10, verbose_name='Número/Identificación'),
        ),
    ]
