# Generated by Django 3.0 on 2019-12-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0002_auto_20191217_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='currentavail',
            field=models.BooleanField(default=True, verbose_name='De alta'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='currentstaff',
            field=models.BooleanField(default=True, verbose_name='En plantilla'),
        ),
    ]
