# Generated by Django 3.0 on 2019-12-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0003_auto_20191218_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=100, verbose_name='Nombre Empresa')),
                ('nif', models.CharField(blank=True, max_length=25, verbose_name='NIF')),
                ('owner', models.CharField(blank=True, max_length=25, verbose_name='Propietario')),
                ('contacto', models.CharField(max_length=100, verbose_name='Persona de contacto')),
                ('fulladdress', models.CharField(max_length=250, verbose_name='Dirección')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['fullname'],
            },
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officeID',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número/Identificación'),
        ),
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('idEquipamiento', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('equipID', models.CharField(max_length=10, unique=True, verbose_name='Referencia/Identificación')),
                ('equipDesc', models.CharField(blank=True, max_length=100, verbose_name='Descripción')),
                ('equipIsavail', models.BooleanField(default=True, verbose_name='Disponible')),
                ('equipLocation', models.CharField(blank=True, max_length=50, verbose_name='Localización')),
                ('equipDepartment', models.CharField(blank=True, max_length=50, verbose_name='Departamento')),
                ('equipManufact', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('equipSAT', models.TextField(blank=True, verbose_name='S.A.T.')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
                ('fk_Proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proveedores', to='gestion_clinica.Proveedor')),
            ],
            options={
                'verbose_name': 'Equipamiento',
                'verbose_name_plural': 'Equipamientos',
                'ordering': ['equipID'],
            },
        ),
    ]
