# Generated by Django 3.0 on 2019-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0004_auto_20191219_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='email2',
            new_name='email',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='equipType',
            field=models.CharField(choices=[('Ordenador', 'Ordenador'), ('Tablet', 'Tablet'), ('Máquinas muscul.', 'Máquinas muscul.'), ('Equipos tratamiento', 'Equipos tratamiento'), ('Enfermería', 'Enfermería'), ('Fungible', 'Fungible'), ('Mobiliario', 'Mobiliario'), ('Papelería', 'Papelería'), ('Limpieza', 'Limpieza'), ('Otros', 'otros')], default='Otros', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailcontacto',
            field=models.EmailField(default='email@valido.com', max_length=75, verbose_name='Correo elect. contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='phonecontacto',
            field=models.PositiveIntegerField(default=0, verbose_name='Teléfono contacto'),
        ),
    ]
