# Generated by Django 3.0 on 2019-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0005_auto_20191219_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='emailcontacto',
            field=models.EmailField(max_length=75, verbose_name='Correo elect. contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phonecontacto',
            field=models.PositiveIntegerField(verbose_name='Teléfono contacto'),
        ),
    ]
