# Generated by Django 3.0 on 2019-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0006_auto_20191219_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='equipType',
            field=models.CharField(choices=[('Ordenador', 'Ordenador'), ('Tablet', 'Tablet'), ('Máquinas muscul.', 'Máquinas muscul.'), ('Equipos tratamiento', 'Equipos tratamiento'), ('Enfermería', 'Enfermería'), ('Fungible', 'Fungible'), ('Mobiliario', 'Mobiliario'), ('Papelería', 'Papelería'), ('Limpieza', 'Limpieza'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Tipo'),
        ),
    ]
