# Generated by Django 3.0 on 2019-12-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0007_auto_20191219_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='stockavail',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad disponible'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='stocklimit',
            field=models.PositiveIntegerField(default=10, verbose_name='Límite para aviso'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='stockwarning',
            field=models.BooleanField(default=True, verbose_name='Aviso de falta de material'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='equipType',
            field=models.CharField(choices=[('infor', 'Equipos informáticos'), ('muscl', 'Máquinas musculación'), ('eqtrm', 'Equipos tratamiento'), ('enfer', 'Enfermería'), ('fung', 'Fungible'), ('mobi', 'Mobiliario'), ('papel', 'Papelería'), ('limp', 'Limpieza'), ('otros', 'Otros')], default='otros', max_length=5, verbose_name='Tipo'),
        ),
    ]
