# Generated by Django 3.0 on 2019-12-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0008_auto_20191220_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamiento',
            name='equipID',
            field=models.CharField(max_length=50, unique=True, verbose_name='Refer./Ident./Num. Serie'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='equipIsavail',
            field=models.BooleanField(default=True, verbose_name='Operativo'),
        ),
    ]
