# Generated by Django 3.0 on 2019-12-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0009_auto_20191220_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='equipManufact',
        ),
        migrations.RemoveField(
            model_name='equipamiento',
            name='equipSAT',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fk_Manufact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantess', to='gestion_clinica.Proveedor'),
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fk_SAT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sats', to='gestion_clinica.Proveedor'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='equipDesc',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
