# Generated by Django 3.0 on 2019-12-21 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0010_auto_20191221_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamiento',
            name='equipLocation',
        ),
        migrations.AddField(
            model_name='equipamiento',
            name='fk_Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='localizaciones', to='gestion_clinica.Consultorio'),
        ),
    ]
