# Generated by Django 3.0 on 2019-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0011_auto_20191221_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='emailcontacto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='phonecontacto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IsSAT',
            field=models.BooleanField(default=True, verbose_name='Es SAT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contactManufact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contactProveedor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contactSAT',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailManufact',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailProveedor',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='emailSAT',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Correo electrónico'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='isManufact',
            field=models.BooleanField(default=True, verbose_name='Es fabricante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='isProveedor',
            field=models.BooleanField(default=True, verbose_name='Es proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='phoneManufact',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='phoneProveedor',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='phoneSAT',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Teléfono fabricante'),
        ),
    ]
