# Generated by Django 3.0 on 2019-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0012_auto_20191221_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='phoneManufact',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phoneProveedor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phoneSAT',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono fabricante'),
        ),
    ]
