# Generated by Django 3.0 on 2019-12-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0013_auto_20191221_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamiento',
            name='stockratio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
