# Generated by Django 3.0 on 2019-12-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0015_auto_20191222_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='area',
            field=models.CharField(blank=True, max_length=150, verbose_name='Area/Ambito'),
        ),
    ]
