# Generated by Django 3.0 on 2019-12-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0016_proveedor_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='IsSAT',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='isSAT',
            field=models.BooleanField(default=False, verbose_name='Es SAT'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='isManufact',
            field=models.BooleanField(default=False, verbose_name='Es fabricante'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='isProveedor',
            field=models.BooleanField(default=False, verbose_name='Es proveedor'),
        ),
    ]
