# Generated by Django 3.0.2 on 2020-01-07 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_clinica', '0018_auto_20200107_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='oto_Profesional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='profesionales', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
