# Generated by Django 3.0.2 on 2020-01-14 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0019_auto_20200107_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='clinicname',
            field=models.CharField(max_length=100, verbose_name='Nombre Clínica'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='fulladdress',
            field=models.CharField(max_length=250, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='numcolegiado',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Colegiado/a'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='ownerfullname',
            field=models.CharField(max_length=100, verbose_name='Nombre Titular'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='phone1',
            field=models.PositiveIntegerField(verbose_name='Teléfono 1'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='phone2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono 2'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='picturefile',
            field=models.ImageField(blank=True, null=True, upload_to='clinica/', verbose_name='LOGO'),
        ),
        migrations.AlterField(
            model_name='clinica',
            name='postcode',
            field=models.PositiveIntegerField(verbose_name='C.Postal'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officeID',
            field=models.CharField(max_length=10, unique=True, verbose_name='Denom./Identif.'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officeIsavail',
            field=models.BooleanField(default=True, verbose_name='Operativo'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='officePhone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='equipIsavail',
            field=models.BooleanField(default=True, verbose_name='Control Operatividad'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='equipType',
            field=models.CharField(choices=[('infor', 'Equipos informáticos'), ('muscl', 'Máquinas musculación'), ('eqtrm', 'Equipos tratamiento'), ('enfer', 'Enfermería'), ('fung', 'Fungible'), ('mobi', 'Mobiliario'), ('papel', 'Papelería'), ('limp', 'Limpieza'), ('otros', 'Otros')], default='otros', max_length=5, verbose_name='Tipo/Clase de Equip./Mat.'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='fk_Manufact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fabricantes', to='gestion_clinica.Proveedor'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='stockavail',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock actual (unids.)'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='stocklimit',
            field=models.PositiveIntegerField(default=10, verbose_name='Límite de aviso (unids.)'),
        ),
        migrations.AlterField(
            model_name='equipamiento',
            name='stockwarning',
            field=models.BooleanField(default=True, verbose_name='Control Stock'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='emailManufact',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='emailProveedor',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='emailSAT',
            field=models.EmailField(blank=True, max_length=75, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='isSAT',
            field=models.BooleanField(default=False, verbose_name='Es S.A.T.'),
        ),
    ]
