# Generated by Django 3.0 on 2019-12-17 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('appdate', models.DateField(default=datetime.date.today, verbose_name='Fecha cita')),
                ('apptime', models.TimeField(default=datetime.time, verbose_name='Hora cita')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Acude', 'Acude'), ('Pasa a consulta', 'Pasa a consulta'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20, verbose_name='Estado cita')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['idCita'],
            },
        ),
    ]
