# Generated by Django 3.0.2 on 2020-01-30 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
        ('gestion_citas', '0001_initial'),
        ('gestion_clinica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fk_Consultorio',
            field=models.ForeignKey(blank=True, limit_choices_to={'officeIsavail': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultorios', to='gestion_clinica.Consultorio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_Paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='gestion_pacientes.Paciente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='fk_Profesional',
            field=models.ForeignKey(blank=True, limit_choices_to={'currentavail': True, 'currentstaff': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='gestion_clinica.Profesional'),
        ),
    ]
