# Generated by Django 3.0.2 on 2020-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_auto_20200117_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.CharField(choices=[('pen', 'Pendiente'), ('att', 'Acude'), ('exm', 'Pasa a consulta'), ('cnl', 'Cancelada')], default='pen', max_length=20, verbose_name='Estado cita'),
        ),
    ]
