# Generated by Django 3.0 on 2019-12-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0002_auto_20191217_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['appdate', 'apptime'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
    ]
