# Generated by Django 3.0 on 2019-12-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clinica', '0001_initial'),
        ('gestion_citas', '0003_auto_20191216_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fk_Consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultorios', to='gestion_clinica.Consultorio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fk_Profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='gestion_clinica.Profesional'),
        ),
    ]
