# Generated by Django 3.0.1 on 2020-01-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0006_notificacita_witherrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='appnotified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Notificada'),
        ),
    ]
