# Generated by Django 3.0.1 on 2020-01-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_citas', '0007_cita_appnotified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='appnotified',
            field=models.BooleanField(default=False, verbose_name='Notificada'),
        ),
    ]
