# Generated by Django 3.0.2 on 2020-01-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(db_index=True, max_length=9, unique=True, verbose_name='DNI')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('familyname', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('birthdate', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha de nacimiento')),
                ('sex', models.CharField(choices=[('No declar.', 'No declar.'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Transexual', 'Transexual'), ('Bisexual', 'Bisexual'), ('Otros', 'Otros')], default='No declarado', max_length=50, verbose_name='Sexo')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('postcode', models.PositiveIntegerField(verbose_name='C. Postal')),
                ('city', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia')),
                ('country', models.CharField(blank=True, default='España', max_length=60, null=True, verbose_name='País')),
                ('email', models.EmailField(blank=True, max_length=75, null=True, verbose_name='Correo electrónico')),
                ('phone1', models.PositiveIntegerField(verbose_name='Teléfono principal')),
                ('phone2', models.PositiveIntegerField(blank=True, null=True, verbose_name='Teléfono alternativo')),
                ('job', models.CharField(blank=True, max_length=20, verbose_name='Ocupación')),
                ('notifyappoint', models.BooleanField(default=False, verbose_name='Notificar citas')),
                ('notifyvia', models.CharField(choices=[('Email', 'Email'), ('Teléfono', 'Teléfono')], default='Email', max_length=10, verbose_name='Notificar por')),
                ('picturefile', models.ImageField(blank=True, null=True, upload_to='pacientes/', verbose_name='Archivo foto')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('firstupdated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('lastupdated', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('modifiedby', models.CharField(blank=True, default='fixuUser', max_length=50, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['familyname', 'name'],
            },
        ),
    ]
