# Generated by Django 3.0.2 on 2020-01-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='notifyvia',
            field=models.CharField(choices=[('eml', 'Email'), ('phn', 'Teléfono')], default='eml', max_length=10, verbose_name='Notificar por'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[('und', 'No declarado'), ('mal', 'Masculino'), ('fem', 'Femenino'), ('oth', 'Otros')], default='und', max_length=50, verbose_name='Sexo'),
        ),
    ]
