# Generated by Django 3.0 on 2019-12-17 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['familyname', 'name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
    ]
