# Generated by Django 3.0 on 2019-12-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_auto_20191217_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[('No declarado', 'No declarado'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Transexual', 'Transexual'), ('Bisexual', 'Bisexual'), ('Otros', 'Otros')], default='No declarado', max_length=50, verbose_name='Sexo'),
        ),
    ]
