# Generated by Django 3.0.1 on 2019-12-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0003_auto_20191219_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='country',
            field=models.CharField(blank=True, default='España', max_length=60, null=True, verbose_name='País'),
        ),
    ]
