# Generated by Django 3.0.1 on 2019-12-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0004_auto_20191228_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sex',
            field=models.CharField(choices=[('No declar.', 'No declar.'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Transexual', 'Transexual'), ('Bisexual', 'Bisexual'), ('Otros', 'Otros')], default='No declarado', max_length=50, verbose_name='Sexo'),
        ),
    ]
