"""
Variables to be used in different apps.

"""

##### VERSION DEL PROGRAMA #####

PROG_VERS = '0.60'

##### CONFIG: VARIABLES DE LA APP GESTION_PACIENTES #####

### Lista de CHOICES para seleccion de ordenacion en el select_pacientes_form ###
selOrder = [
    ('A', 'Apellidos (por defecto)'),
    ('N', 'Nombre'),
    ('D', 'DNI'),
    ('P', 'Paciente ID')
]

### Lista de CHOICES para seleccion de sexo en gestion_pacientes/models.py ###
sexDef = [
    ('No declarado', 'No declarado'),
    ('Masculino', 'Masculino'),
    ('Femenino', 'Femenino'),
    ('Transexual', 'Transexual'),
    ('Bisexual', 'Bisexual'),
    ('Otros', 'Otros')
]

### Lista de CHOICES para seleccion de modos de comunicar las citas en gestion_pacientes/models.py ###
modeVia = [
    ('Email', 'Email'),
    ('Teléfono', 'Teléfono')
]

### Lista de CHOICES para seleccion de paises en gestion_pacientes/models.py ###
countries = [
    ('ESPAÑA', 'ESPAÑA'),
    ('AFGANISTAN', 'AFGANISTAN'),
    ('ALBANIA', 'ALBANIA'),
    ('ALEMANIA', 'ALEMANIA'),
    ('ANDORRA', 'ANDORRA'),
    ('ANGOLA', 'ANGOLA'),
    ('ANGUILLA', 'ANGUILLA'),
    ('ANTIGUA Y BARBUDA', 'ANTIGUA Y BARBUDA'),
    ('ANTILLAS HOLANDESAS', 'ANTILLAS HOLANDESAS'),
    ('ARABIA SAUDI', 'ARABIA SAUDI'),
    ('ARGELIA', 'ARGELIA'),
    ('ARGENTINA', 'ARGENTINA'),
    ('ARMENIA', 'ARMENIA'),
    ('ARUBA', 'ARUBA'),
    ('AUSTRALIA', 'AUSTRALIA'),
    ('AUSTRIA', 'AUSTRIA'),
    ('AZERBAIYAN', 'AZERBAIYAN'),
    ('BAHAMAS', 'BAHAMAS'),
    ('BAHREIN', 'BAHREIN'),
    ('BANGLADESH', 'BANGLADESH'),
    ('BARBADOS', 'BARBADOS'),
    ('BELARUS', 'BELARUS'),
    ('BELGICA', 'BELGICA'),
    ('BELICE', 'BELICE'),
    ('BENIN', 'BENIN'),
    ('BERMUDAS', 'BERMUDAS'),
    ('BHUTÁN', 'BHUTÁN'),
    ('BOLIVIA', 'BOLIVIA'),
    ('BOSNIA Y HERZEGOVINA', 'BOSNIA Y HERZEGOVINA'),
    ('BOTSWANA', 'BOTSWANA'),
    ('BRASIL', 'BRASIL'),
    ('BRUNEI', 'BRUNEI'),
    ('BULGARIA', 'BULGARIA'),
    ('BURKINA FASO', 'BURKINA FASO'),
    ('BURUNDI', 'BURUNDI'),
    ('CABO VERDE', 'CABO VERDE'),
    ('CAMBOYA', 'CAMBOYA'),
    ('CAMERUN', 'CAMERUN'),
    ('CANADA', 'CANADA'),
    ('CHAD', 'CHAD'),
    ('CHILE', 'CHILE'),
    ('CHINA', 'CHINA'),
    ('CHIPRE', 'CHIPRE'),
    ('COLOMBIA', 'COLOMBIA'),
    ('COMORES', 'COMORES'),
    ('CONGO', 'CONGO'),
    ('COREA', 'COREA'),
    ('COREA DEL NORTE ', 'COREA DEL NORTE '),
    ('COSTA DE MARFIL', 'COSTA DE MARFIL'),
    ('COSTA RICA', 'COSTA RICA'),
    ('CROACIA', 'CROACIA'),
    ('CUBA', 'CUBA'),
    ('DINAMARCA', 'DINAMARCA'),
    ('DJIBOUTI', 'DJIBOUTI'),
    ('DOMINICA', 'DOMINICA'),
    ('ECUADOR', 'ECUADOR'),
    ('EGIPTO', 'EGIPTO'),
    ('EL SALVADOR', 'EL SALVADOR'),
    ('EMIRATOS ARABES UNIDOS', 'EMIRATOS ARABES UNIDOS'),
    ('ERITREA', 'ERITREA'),
    ('ESLOVENIA', 'ESLOVENIA'),
    ('ESTADOS UNIDOS DE AMERICA', 'ESTADOS UNIDOS DE AMERICA'),
    ('ESTONIA', 'ESTONIA'),
    ('ETIOPIA', 'ETIOPIA'),
    ('FIJI', 'FIJI'),
    ('FILIPINAS', 'FILIPINAS'),
    ('FINLANDIA', 'FINLANDIA'),
    ('FRANCIA', 'FRANCIA'),
    ('GABON', 'GABON'),
    ('GAMBIA', 'GAMBIA'),
    ('GEORGIA', 'GEORGIA'),
    ('GHANA', 'GHANA'),
    ('GIBRALTAR', 'GIBRALTAR'),
    ('GRANADA', 'GRANADA'),
    ('GRECIA', 'GRECIA'),
    ('GROENLANDIA', 'GROENLANDIA'),
    ('GUADALUPE', 'GUADALUPE'),
    ('GUAM', 'GUAM'),
    ('GUATEMALA', 'GUATEMALA'),
    ('GUAYANA FRANCESA', 'GUAYANA FRANCESA'),
    ('GUERNESEY', 'GUERNESEY'),
    ('GUINEA', 'GUINEA'),
    ('GUINEA-BISSAU', 'GUINEA-BISSAU'),
    ('GUINEA ECUATORIAL', 'GUINEA ECUATORIAL'),
    ('GUYANA', 'GUYANA'),
    ('HAITI', 'HAITI'),
    ('HONDURAS', 'HONDURAS'),
    ('HONG KONG', 'HONG KONG'),
    ('HUNGRIA', 'HUNGRIA'),
    ('INDIA', 'INDIA'),
    ('INDONESIA', 'INDONESIA'),
    ('IRAN', 'IRAN'),
    ('IRAQ', 'IRAQ'),
    ('IRLANDA', 'IRLANDA'),
    ('ISLA DE MAN', 'ISLA DE MAN'),
    ('ISLANDIA', 'ISLANDIA'),
    ('ISLA NORFOLK', 'ISLA NORFOLK'),
    ('ISLAS ALAND', 'ISLAS ALAND'),
    ('ISLAS CAIMÁN', 'ISLAS CAIMÁN'),
    ('ISLAS COOK', 'ISLAS COOK'),
    ('ISLAS DEL CANAL', 'ISLAS DEL CANAL'),
    ('ISLAS FEROE', 'ISLAS FEROE'),
    ('ISLAS MALVINAS', 'ISLAS MALVINAS'),
    ('ISLAS MARIANAS DEL NORTE', 'ISLAS MARIANAS DEL NORTE'),
    ('ISLAS MARSHALL', 'ISLAS MARSHALL'),
    ('ISLAS PITCAIRN', 'ISLAS PITCAIRN'),
    ('ISLAS SALOMON', 'ISLAS SALOMON'),
    ('ISLAS TURCAS Y CAICOS', 'ISLAS TURCAS Y CAICOS'),
    ('ISLAS VIRGENES BRITANICAS', 'ISLAS VIRGENES BRITANICAS'),
    ('ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS'),
    ('ISRAEL', 'ISRAEL'),
    ('ITALIA', 'ITALIA'),
    ('JAMAICA', 'JAMAICA'),
    ('JAPON', 'JAPON'),
    ('JERSEY', 'JERSEY'),
    ('JORDANIA', 'JORDANIA'),
    ('KAZAJSTAN', 'KAZAJSTAN'),
    ('KENIA', 'KENIA'),
    ('KIRGUISTAN', 'KIRGUISTAN'),
    ('KIRIBATI', 'KIRIBATI'),
    ('KUWAIT', 'KUWAIT'),
    ('LAOS', 'LAOS'),
    ('LESOTHO', 'LESOTHO'),
    ('LETONIA', 'LETONIA'),
    ('LIBANO', 'LIBANO'),
    ('LIBERIA', 'LIBERIA'),
    ('LIBIA', 'LIBIA'),
    ('LIECHTENSTEIN', 'LIECHTENSTEIN'),
    ('LITUANIA', 'LITUANIA'),
    ('LUXEMBURGO', 'LUXEMBURGO'),
    ('MACAO', 'MACAO'),
    ('MACEDONIA ', 'MACEDONIA '),
    ('MADAGASCAR', 'MADAGASCAR'),
    ('MALASIA', 'MALASIA'),
    ('MALAWI', 'MALAWI'),
    ('MALDIVAS', 'MALDIVAS'),
    ('MALI', 'MALI'),
    ('MALTA', 'MALTA'),
    ('MARRUECOS', 'MARRUECOS'),
    ('MARTINICA', 'MARTINICA'),
    ('MAURICIO', 'MAURICIO'),
    ('MAURITANIA', 'MAURITANIA'),
    ('MAYOTTE', 'MAYOTTE'),
    ('MEXICO', 'MEXICO'),
    ('MICRONESIA', 'MICRONESIA'),
    ('MOLDAVIA', 'MOLDAVIA'),
    ('MONACO', 'MONACO'),
    ('MONGOLIA', 'MONGOLIA'),
    ('MONTENEGRO', 'MONTENEGRO'),
    ('MONTSERRAT', 'MONTSERRAT'),
    ('MOZAMBIQUE', 'MOZAMBIQUE'),
    ('MYANMAR', 'MYANMAR'),
    ('NAMIBIA', 'NAMIBIA'),
    ('NAURU', 'NAURU'),
    ('NEPAL', 'NEPAL'),
    ('NICARAGUA', 'NICARAGUA'),
    ('NIGER', 'NIGER'),
    ('NIGERIA', 'NIGERIA'),
    ('NIUE', 'NIUE'),
    ('NORUEGA', 'NORUEGA'),
    ('NUEVA CALEDONIA', 'NUEVA CALEDONIA'),
    ('NUEVA ZELANDA', 'NUEVA ZELANDA'),
    ('OMAN', 'OMAN'),
    ('OTROS PAISES O TERRITORIOS DE AFRICA', 'OTROS PAISES O TERRITORIOS DE AFRICA'),
    ('OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE', 'OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE'),
    ('OTROS PAISES O TERRITORIOS DE ASIA', 'OTROS PAISES O TERRITORIOS DE ASIA'),
    ('OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA', 'OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA'),
    ('OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL', 'OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL'),
    ('OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA', 'OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA'),
    ('OTROS PAISES O TERRITORIOS DE OCEANIA', 'OTROS PAISES O TERRITORIOS DE OCEANIA'),
    ('OTROS PAISES O TERRITORIOS  DE SUDAMERICA', 'OTROS PAISES O TERRITORIOS  DE SUDAMERICA'),
    ('PAISES BAJOS', 'PAISES BAJOS'),
    ('PAKISTAN', 'PAKISTAN'),
    ('PALAOS', 'PALAOS'),
    ('PALESTINA', 'PALESTINA'),
    ('PANAMA', 'PANAMA'),
    ('PAPUA NUEVA GUINEA', 'PAPUA NUEVA GUINEA'),
    ('PARAGUAY', 'PARAGUAY'),
    ('PERU', 'PERU'),
    ('POLINESIA FRANCESA', 'POLINESIA FRANCESA'),
    ('POLONIA', 'POLONIA'),
    ('PORTUGAL', 'PORTUGAL'),
    ('PUERTO RICO', 'PUERTO RICO'),
    ('QATAR', 'QATAR'),
    ('REINO UNIDO', 'REINO UNIDO'),
    ('REP.DEMOCRATICA DEL CONGO', 'REP.DEMOCRATICA DEL CONGO'),
    ('REPUBLICA CENTROAFRICANA', 'REPUBLICA CENTROAFRICANA'),
    ('REPUBLICA CHECA', 'REPUBLICA CHECA'),
    ('REPUBLICA DOMINICANA', 'REPUBLICA DOMINICANA'),
    ('REPUBLICA ESLOVACA', 'REPUBLICA ESLOVACA'),
    ('REUNION', 'REUNION'),
    ('RUANDA', 'RUANDA'),
    ('RUMANIA', 'RUMANIA'),
    ('RUSIA', 'RUSIA'),
    ('SAHARA OCCIDENTAL', 'SAHARA OCCIDENTAL'),
    ('SAMOA', 'SAMOA'),
    ('SAMOA AMERICANA', 'SAMOA AMERICANA'),
    ('SAN BARTOLOME', 'SAN BARTOLOME'),
    ('SAN CRISTOBAL Y NIEVES', 'SAN CRISTOBAL Y NIEVES'),
    ('SAN MARINO', 'SAN MARINO'),
    ('SAN MARTIN (PARTE FRANCESA)', 'SAN MARTIN (PARTE FRANCESA)'),
    ('SAN PEDRO Y MIQUELON ', 'SAN PEDRO Y MIQUELON '),
    ('SANTA HELENA', 'SANTA HELENA'),
    ('SANTA LUCIA', 'SANTA LUCIA'),
    ('SANTA SEDE', 'SANTA SEDE'),
    ('SANTO TOME Y PRINCIPE', 'SANTO TOME Y PRINCIPE'),
    ('SAN VICENTE Y LAS GRANADINAS', 'SAN VICENTE Y LAS GRANADINAS'),
    ('SENEGAL', 'SENEGAL'),
    ('SERBIA', 'SERBIA'),
    ('SEYCHELLES', 'SEYCHELLES'),
    ('SIERRA LEONA', 'SIERRA LEONA'),
    ('SINGAPUR', 'SINGAPUR'),
    ('SIRIA', 'SIRIA'),
    ('SOMALIA', 'SOMALIA'),
    ('SRI LANKA', 'SRI LANKA'),
    ('SUDAFRICA', 'SUDAFRICA'),
    ('SUDAN', 'SUDAN'),
    ('SUECIA', 'SUECIA'),
    ('SUIZA', 'SUIZA'),
    ('SURINAM', 'SURINAM'),
    ('SVALBARD Y JAN MAYEN', 'SVALBARD Y JAN MAYEN'),
    ('SWAZILANDIA', 'SWAZILANDIA'),
    ('TADYIKISTAN', 'TADYIKISTAN'),
    ('TAILANDIA', 'TAILANDIA'),
    ('TANZANIA', 'TANZANIA'),
    ('TIMOR ORIENTAL', 'TIMOR ORIENTAL'),
    ('TOGO', 'TOGO'),
    ('TOKELAU', 'TOKELAU'),
    ('TONGA', 'TONGA'),
    ('TRINIDAD Y TOBAGO', 'TRINIDAD Y TOBAGO'),
    ('TUNEZ', 'TUNEZ'),
    ('TURKMENISTAN', 'TURKMENISTAN'),
    ('TURQUIA', 'TURQUIA'),
    ('TUVALU', 'TUVALU'),
    ('UCRANIA', 'UCRANIA'),
    ('UGANDA', 'UGANDA'),
    ('URUGUAY', 'URUGUAY'),
    ('UZBEKISTAN', 'UZBEKISTAN'),
    ('VANUATU', 'VANUATU'),
    ('VENEZUELA', 'VENEZUELA'),
    ('VIETNAM', 'VIETNAM'),
    ('WALLIS Y FORTUNA', 'WALLIS Y FORTUNA'),
    ('YEMEN', 'YEMEN'),
    ('ZAMBIA', 'ZAMBIA'),
    ('ZIMBABWE', 'ZIMBABWE')
 ]

##### CONFIG: VARIABLES DE LA APP GESTION_CITAS #####

# Hora de comienzo de las consultas en formato string: HH:MM
HORA_COMIENZO = '13:00'

# Hora de finalización de las consultas en formato string: HH:MM
HORA_FINAL = '19:30'

# Duración en MINUTOS aproximada de cada ventana de consulta int: N
DURACION_CONSULTA = 30

# Notificar citas con ESTOS dias de antelación int: N
NOTIFICAR_CON = 3

##### Choices para el status de las citas #####
citasStatus = [
    ('Pendiente', 'Pendiente'),
    ('Acude', 'Acude'),
    ('Pasa a consulta', 'Pasa a consulta'),
    ('Cancelada', 'Cancelada')
]
##### CONFIG: VARIABLES DE LA APP GESTION_CLINICA #####

##### Choices para el tipo de material/equipamiento #####
selTipoEquip = [
    ('infor', 'Equipos informáticos'),
    ('muscl', 'Máquinas musculación'),
    ('eqtrm', 'Equipos tratamiento'),
    ('enfer', 'Enfermería'),
    ('fung', 'Fungible'),
    ('mobi', 'Mobiliario'),
    ('papel', 'Papelería'),    
    ('limp', 'Limpieza'),
    ('otros', 'Otros'),
]
